# Generated by Django 3.0.5 on 2020-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_announcements_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_description', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
