# Generated by Django 3.0.5 on 2020-06-25 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200625_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='img',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title_description',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
