# Generated by Django 3.0.5 on 2020-06-25 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20200625_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='resource',
            name='url_title',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
