# Generated by Django 3.0.5 on 2020-06-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20200625_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='url_title',
            field=models.CharField(max_length=500),
        ),
    ]
