# Generated by Django 3.0.5 on 2020-06-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200625_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='img',
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource',
            field=models.URLField(max_length=100),
        ),
    ]
